site_name: Bc-pipelines
docs_dir: docs
nav:
  - Home: index.md
  - Todo: todo.md
  - BC_software: 
    - Overview: BCsoftware/intro.md
    - BC_manager: BCsoftware/BC_manager.md
  - BC_scripts:
    - Overview: BCscripts/intro.md

theme:
  name: readthedocs