site_name: Bc-pipelines
docs_dir: docs
nav:
  - Home: index.md
  - BC_software: 
    - Intro: BCsoftware/intro.md
    - BC_manager: BCssoftware/BC_manager.md
  - BC_scripts:
    - Intro: BCscripts/intro.md
  - Todo: todo.md
theme:
  name: readthedocs