# _config.yml

# Site settings
title: BC-pipelines documentation
description: Documentation for the project
baseurl: /docs # the subpath of your site, e.g. /docs, or leave it empty for the root

# Build settings
markdown: kramdown
theme: jekyll-theme-readthedocs

# Navigation
nav:
  - About: index.md
  - BC_software: BC_software.md 
  - BC_scripts: BC_scripts.md

