title: Bc-pipelines documentation
description: A documentation for the parallelization of basecalling through pipelines
remote_theme: just-the-docs/just-the-docs
url: https://rodtol.github.io/BC-pipelines/

nav:
  - Home
  - Configuration file
  - Basecalling-pipeline
  - BC_software
  - BC_scripts
  - TODO

callouts_level: quiet # or loud
callouts:
  warning:
    title: Warning ⚠️
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false