name: Sync README

on:
  push:
    branches:
      - master

jobs:
  copy-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check for changes in docs/index.md
      id: check_changes
      run: |
        if [[ -n $(git status --porcelain docs/index.md) ]]; then
          echo "Docs/index.md has changes."
          echo "::set-output name=changes::true"
        else
          echo "No changes in docs/index.md."
          echo "::set-output name=changes::false"
        fi

    - name: Copy Docs to README
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        cp docs/index.md README.md
        git add README.md
        git commit -m "Update README.md from docs/index.md"

    - name: Push Changes
      if: steps.check_changes.outputs.changes == 'true'
      run: git push
