name: Sync README

on:
  push:
    branches:
      - master

jobs:
  copy-readme:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Get changes
      id: check_changes
      uses: tj-actions/changed-files@v42.0.5
    
    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.check_changes.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done

    - name: Copy index.md to README
      if: contains(steps.check_changes.outputs.all_changed_files, 'docs/index.md')
      run: |
        cp docs/index.md README.md
        sed -i 's/assets\/area_for_white_bkg.png/docs\/assets\/logo-area.png/g' "README.md"
        sed -i '/---/,/---/d' README.md
    
    - name: Replace links in README
      if: contains(steps.check_changes.outputs.all_changed_files, 'docs/index.md')
      run: |
        replacements=(
            "BC_software.md:docs/BC_software.md"
            "BC_scripts.md:docs/BC_scripts.md"
            "Basecalling-pipeline.md:docs/Basecalling-pipeline.md"
            "configurations.md:docs/configurations.md"
        )
    
        for replacement in "${replacements[@]}"; do
            old_text="${replacement%%:*}"
            new_text="${replacement#*:}"
            sed -i "s#\[$old_text\]($old_text)#\[$old_text\]($new_text)#g" "README.md"
        done
      

  
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5