name: Sync README

on:
  push:
    branches:
      - master

jobs:
  copy-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Check for changes in docs/index.md
      id: check_changes
      uses: tj-actions/changed-files@v42.0.5

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.check_changes.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done


