name: Sync README

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy Docs to README
      run: |
        # Check if docs/index.md is modified
        if [[ $(git diff --name-only ${{ github.sha }}^ ${{ github.sha }}) == 'docs/index.md' ]]; then
          # Copy docs/index.md to README.md
          cp docs/index.md README.md
          # Stage changes
          git add README.md
          # Commit changes
          git commit -m "Update README.md from docs/index.md"
        else
          echo "No changes in docs/index.md. Skipping the copy operation."
        fi

    - name: Push Changes
      if: git diff --name-only ${{ github.sha }}^ ${{ github.sha }} == 'docs/index.md'
      run: git push
