name: Sync README

on:
  push:
    branches:
      - master

jobs:
  copy-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy docs/index.md to README.md
      run: |
        cp docs/index.md README.md
      if: github.event_name == 'push' && github.event_path == 'docs/index.md'
